AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 846282225459

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: donatoaz
      AccountId: '846282225459'
      RootEmail: donatoaz@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationFormationBuildAccessRole

  ProdOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: ProdOU
      Accounts: !Ref ProdAccount

  DevOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: DevOU
      Accounts: !Ref DevAccount

  DevAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Dev Account
      AccountId: '834651025166'
      RootEmail: donatoaz+aws_dev@gmail.com

  ProdAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Prod Account
      AccountId: '616794725756'
      RootEmail: donatoaz+aws_prod@gmail.com

  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'
        
  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-east-1
                  - us-west-2
                  - sa-east-1
        

